### ISSUE TITLE
Does the promu support setting the gcflags?

### ISSUE THREAD

**Issue by kiragoo** [prometheus/promu#235]
First of all, thanks for the project "prometheus/promu".

Recently I used the gdb to debug the smartctl_exporter which was built by the tool "promu".

The .promu.yaml for smartctl_exporter  as blows:
```yaml
go:
    # This must match .circle/config.yml.
    version: 1.18
repository:
    path: github.com/prometheus-community/smartctl_exporter
build:
    binaries:
        - name: smartctl_exporter
    flags: -a -tags 'netgo static_build'
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
        - NOTICE
```
While debugging the smartctl_exporter with gdb, I found the variable "devices" is **"optimized out"**.
![图片](https://user-images.githubusercontent.com/7400711/185929867-d6de2416-1da1-4ec5-930d-916c25eb934d.png)

I just want to print the variable "devices", maybe turning off optimization and inlining in Go gc compilers could solve the problem.

So, my question is that "does the promu support setting the **"gcflags"** ?

I'll be appreciate for your help ^_^.
