### ISSUE TITLE
Use a single list of platforms to crossbuild

### ISSUE THREAD

**Issue by sdurrheimer** [prometheus/promu#3]
then translate it to use the right `prom/golang-builder` image for each platforms
```
crossbuild:
    platforms:
        main:
            - linux/amd64
            - linux/386
            - darwin/amd64
            - darwin/386
            - windows/amd64
            - windows/386
        arm:
            - linux/arm
            - linux/arm64
        powerpc:
            - linux/ppc64
            - linux/ppc64le
```
to
```
crossbuild:
    platforms:
        - linux/amd64
        - linux/386
        - darwin/amd64
        - darwin/386
        - windows/amd64
        - windows/386
        - linux/arm
        - linux/arm64
        - linux/ppc64
        - linux/ppc64le
```
